### ISSUE TITLE
fails when docker container was built with ENTRYPOINT

### ISSUE THREAD

**Issue by paulczar** [docker-archive/openstack-docker#9]
looks like the `cmd: ....` line (in the userdata file) calls docker and runs the command with `/bin/sh -c`  this means any container that has an entrypoint will fail, as it is pushing the `/bin/sh -c` as a argument at that point.

**Comment by samalba** [comment]
It's a really good point. I'll look if I can inspect the image for a default command before overriding it.

**Comment by samalba** [comment]
Fixed
